### PR TITLE
Improve documentation

### PR DESCRIPTION
**Pull request by toolness**
This improves our documentation by removing almost all of the gatsby starter project content from the README and adding our own "quick start".

I also added notes on how to get the Space ID and API key for our site.  I found a [Contentful thread](https://www.contentfulcommunity.com/t/should-i-keep-access-tokens-secret/457/3) that advises against putting this information into a repository, even though it isn't actually security related for us; I've followed this advice in this PR, but I'm honestly not sure how I feel about it because **this repository is essentially useless if it doesn't integrate with our specific space on Contentful**.  Therefore, not committing these security-insensitive configuration variables just increases the barrier for contributions to our site (volunteers and employees will have to contact us to get the information) without actually improving security in any meaningful way, but that's just my 2 cents.

### CODE REVIEW

**Comment by toolness** [comment]
Oh, I also think we should have a "deployment" section in the README but I don't actually know how the site is deployed.  From the GitHub checks it looks like it's done through Netlify though... @sraby can you add a section to the README that documents this, maybe?

**Comment by sraby** [comment]
thank you @toolness! this has been a to-do for a while so happy to have your support on that. Ill try and carve out time to add the documentation about Netlify. Also, are you suggesting that we actually publish our Contentful tokens so folks can contribute? Maybe a middle ground could be linking our email so folks can request the token if they want to play around using our site's content?

**Comment by sraby** [comment]
@toolness do you think this is enough context to include about Deployment?

**Comment by toolness** [comment]
> Also, are you suggesting that we actually publish our Contentful tokens so folks can contribute? Maybe a middle ground could be linking our email so folks can request the token if they want to play around using our site's content?

I guess it's something we could discuss in the future--for now just merging this PR as-is is probably best!

**Comment by toolness** [comment]
yeah the deployment section looks great!  Feel free to merge this if you think it looks good.

**Pull request merged**
