### PR TITLE
add underline on hover for navbar menu links

### PR DESCRIPTION
**Pull request by austensen**
[sc-10218]

image

### CODE REVIEW

**Comment by austensen** [comment]
[sc-10475]

**Review by sraby — APPROVED** [review]
looks good

**Review by shakao — APPROVED** [review]

**Comment by shakao** [comment]
maybe also add this one to the shortcut card for unifying link styles? feels like it could be similar to the underline for article titles

**Comment by austensen** [comment]
> [Shortcut Story #10475: clarify link styles for design system](https://app.shortcut.com/justfixnyc/story/10475/clarify-link-styles-for-design-system).

Yeah good idea - here's a card for that and links to both of those PRs as reference

**Pull request merged**
